on:
  push:
    paths:
      - 'pom.xml'
      - '.github/workflows/deploy.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          server-id: softalks-pom
      - env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES }}
        run: mvn -X --batch-mode --update-snapshots deploy
        
